.TH "Final Software.speech_engine" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Final Software.speech_engine
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBspeak\fP (speech_text)"
.br
.RI "Speech engine based on pyttsx3, performs text-to-speech\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Final Software\&.speech_engine\&.speak ( speech_text)"

.PP
Speech engine based on pyttsx3, performs text-to-speech\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspeech_text\fP text to be translated into speech 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
