.TH "Final Software.lm_control" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Final Software.lm_control
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBcontrol_equipment\fP (machine, action, queue)"
.br
.RI "Function that controls machinery connected to the MOXA device by turning them on and off\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Final Software\&.lm_control\&.control_equipment ( machine,  action,  queue)"

.PP
Function that controls machinery connected to the MOXA device by turning them on and off\&. 
.PP
\fBParameters:\fP
.RS 4
\fImachine\fP name of machine to be interfaced 
.br
\fIaction\fP action to be performed on machine [on, off] 
.br
\fIqueue\fP queue used to update GUI thread 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
