.TH "Final Software.save_file" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Final Software.save_file
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsave_file\fP (conv_hist, trans_hist)"
.br
.RI "Function that saves files to directory on Desktop\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Final Software\&.save_file\&.save_file ( conv_hist,  trans_hist)"

.PP
Function that saves files to directory on Desktop\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconv_hist\fP log of conversation history 
.br
\fItrans_hist\fP transcription history 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
