.TH "Final Software.bt_setup" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Final Software.bt_setup
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsetup_bt\fP ()"
.br
.RI "Function that discovers bt devices and pairs with them Automates manual pairing and connection\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "def Final Software\&.bt_setup\&.setup_bt ()"

.PP
Function that discovers bt devices and pairs with them Automates manual pairing and connection\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
