.TH "C:/Users/LIU181/Desktop/Final Software/gcp_stt.py" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/LIU181/Desktop/Final Software/gcp_stt.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFinal Software\&.gcp_stt\&.MicrophoneStream\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinal Software\&.gcp_stt\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBFinal Software\&.gcp_stt\&.listen_print_loop\fP (responses, queue)"
.br
.RI "Obtain the HTTP response from Google Speech API and iterate through responses until user decides to exit the system\&. "
.ti -1c
.RI "def \fBFinal Software\&.gcp_stt\&.streaming_transcribe\fP (queue)"
.br
.RI "Function that performs speech-to-text on streaming audio input\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
