.TH "C:/Users/LIU181/Desktop/Final Software/lm_status.py" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/LIU181/Desktop/Final Software/lm_status.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinal Software\&.lm_status\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBFinal Software\&.lm_status\&.get_lm_status\fP (lab_machine_status, lab_machine, queue)"
.br
.RI "Function that polls lab machine status and returns whether it is on or off\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
