.TH "C:/Users/LIU181/Desktop/Final Software/td_utils.py" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/LIU181/Desktop/Final Software/td_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinal Software\&.td_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBFinal Software\&.td_utils\&.graph_spectrogram\fP (wav_file)"
.br
.RI "Calculate and plot spectrogram of a wav audio file\&. "
.ti -1c
.RI "def \fBFinal Software\&.td_utils\&.get_wav_info\fP (wav_file)"
.br
.RI "Return sampling rate and data read from wav file\&. "
.ti -1c
.RI "def \fBFinal Software\&.td_utils\&.match_target_amplitude\fP (sound, target_dBFS)"
.br
.RI "Function to standardise the volume of audio clips\&. "
.ti -1c
.RI "def \fBFinal Software\&.td_utils\&.load_raw_audio\fP ()"
.br
.RI "Function to load raw audio files for speech synthesis\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
