.TH "C:/Users/LIU181/Desktop/Final Software/twd_imitate.py" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/LIU181/Desktop/Final Software/twd_imitate.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinal Software\&.twd_imitate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBFinal Software\&.twd_imitate\&.twd_imitate\fP (queue)"
.br
.RI "Function that imitates the functionality of the trigger word detection engine waits 5 seconds before returning, mimicking the system waking up after detecting trigger words\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFinal Software\&.twd_imitate\&.speech_engine\fP = importlib\&.import_module('speech_engine')"
.br
.RI "imported \fBspeech_engine\fP module "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
