.TH "C:/Users/LIU181/Desktop/Final Software/twd_engine.py" 3 "Fri Feb 22 2019" "VLAS_AGENT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/LIU181/Desktop/Final Software/twd_engine.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBFinal Software\&.twd_engine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBFinal Software\&.twd_engine\&.detect_triggerword_spectrum\fP (model, x)"
.br
.RI "Function to predict existence of trigger word in spectrogram sample\&. "
.ti -1c
.RI "def \fBFinal Software\&.twd_engine\&.has_triggerword\fP (predictions, chunk_duration, feed_duration, threshold=0\&.5)"
.br
.RI "Function to predict if trigger word exists\&. "
.ti -1c
.RI "def \fBFinal Software\&.twd_engine\&.get_spectrogram\fP (data)"
.br
.RI "Function that generates frequency spectrogram based on input audio data\&. "
.ti -1c
.RI "def \fBFinal Software\&.twd_engine\&.detect_twd\fP ()"
.br
.RI "Function to start listening to streaming microphone input and predict if trigger word is present\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VLAS_AGENT from the source code\&.
